const tokenColor = name => `var(--${name})`;

module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts,tsx}'],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      white: tokenColor('neutral-0'),
      black: tokenColor('neutral-950'),
      brand: {
        50: tokenColor('brand-50'),
        100: tokenColor('brand-100'),
        200: tokenColor('brand-200'),
        300: tokenColor('brand-300'),
        400: tokenColor('brand-400'),
        500: tokenColor('brand-500'),
        600: tokenColor('brand-600'),
        700: tokenColor('brand-700'),
        800: tokenColor('brand-800'),
        900: tokenColor('brand-900'),
      },
      neutral: {
        0: tokenColor('neutral-0'),
        50: tokenColor('neutral-50'),
        100: tokenColor('neutral-100'),
        200: tokenColor('neutral-200'),
        300: tokenColor('neutral-300'),
        400: tokenColor('neutral-400'),
        500: tokenColor('neutral-500'),
        600: tokenColor('neutral-600'),
        700: tokenColor('neutral-700'),
        800: tokenColor('neutral-800'),
        900: tokenColor('neutral-900'),
        950: tokenColor('neutral-950'),
      },
      success: {
        50: tokenColor('success-50'),
        500: tokenColor('success-500'),
      },
      error: {
        50: tokenColor('error-50'),
        500: tokenColor('error-500'),
      },
      warning: {
        50: tokenColor('warning-50'),
        500: tokenColor('warning-500'),
      },
      info: {
        50: tokenColor('info-50'),
        500: tokenColor('info-500'),
      },
      surface: {
        base: tokenColor('surface-base'),
        raised: tokenColor('surface-raised'),
        overlay: tokenColor('surface-overlay'),
        sunken: tokenColor('surface-sunken'),
      },
    },
    spacing: {
      0: '0px',
      px: '1px',
      0.5: '2px',
      1: 'var(--space-1)',
      2: 'var(--space-2)',
      3: 'var(--space-3)',
      4: 'var(--space-4)',
      5: 'var(--space-5)',
      6: 'var(--space-6)',
      7: 'var(--space-7)',
      8: 'var(--space-8)',
      9: 'var(--space-9)',
      10: 'var(--space-10)',
      11: 'var(--space-11)',
      12: 'var(--space-12)',
    },
    boxShadow: {
      none: 'var(--elevation-none)',
      sm: 'var(--elevation-sm)',
      md: 'var(--elevation-md)',
      lg: 'var(--elevation-lg)',
    },
    flex: {
      auto: '1 1 auto',
      1: '1 1 0',
      2: '2 2 0',
    },
    fill: {
      current: 'currentColor',
    },
    stroke: {
      current: 'currentColor',
    },
    extend: {
      fontSize: {
        '2xs': ['0.625rem', '0.75rem'],
        display: ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        'heading-lg': ['22px', { lineHeight: '1.3', fontWeight: '600' }],
        'heading-md': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'heading-sm': ['15px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['15px', { lineHeight: '1.5', fontWeight: '400' }],
        body: ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        overline: ['11px', { lineHeight: '1.4', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
