import { CdkAccordionModule } from '@angular/cdk/accordion';
import { DialogModule } from '@angular/cdk/dialog';
import { CdkDrag, CdkDragHandle, CdkDropList } from '@angular/cdk/drag-drop';
import { CdkMenuModule } from '@angular/cdk/menu';
import { NgOptimizedImage } from '@angular/common';
import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatDialogModule } from '@angular/material/dialog';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatRadioModule } from '@angular/material/radio';
import { EffectsModule } from '@ngrx/effects';
import { StoreModule } from '@ngrx/store';
import { SharedModule } from 'src/app/shared/shared.module';
import { SelectControlCounterModule } from '../../shared/component/control/select-control-counter/select-control-counter.module';
import { TimeSelectControlModule } from '../../shared/component/control/time-select-control/time-select-control.module';
import { SettingsCoreAdminNoticesComponent } from './settings-core/settings-core-admin-notices/settings-core-admin-notices.component';
import { SettingsCoreDeleteNoticeComponent } from './settings-core/settings-core-admin-notices/settings-core-delete-notice/settings-core-delete-notice.component';
import { SettingsCoreNewNoticesComponent } from './settings-core/settings-core-admin-notices/settings-core-new-notices/settings-core-new-notices.component';
import { SettingsCoreNoticeListComponent } from './settings-core/settings-core-admin-notices/settings-core-notice-list/settings-core-notice-list.component';
import { SettingsCoreAdminsCreateDialogComponent } from './settings-core/settings-core-admins/settings-core-admins-create-admin-dialog/settings-core-admins-create-dialog.component';
import { SettingsCoreAdminsComponent } from './settings-core/settings-core-admins/settings-core-admins.component';
import { SettingsCoreCompaniesCompanyComponent } from './settings-core/settings-core-companies/settings-core-companies-company/settings-core-companies-company.component';
import { SettingsCoreCompaniesCreateCompanyDialogComponent } from './settings-core/settings-core-companies/settings-core-companies-create-company-dialog/settings-core-companies-create-company-dialog.component';
import { SettingsCoreCompaniesCreateFleetAccessDialogComponent } from './settings-core/settings-core-companies/settings-core-companies-create-fleet-access-dialog/settings-core-companies-create-fleet-access-dialog.component';
import { SettingsCoreCompaniesDeleteCompanyDialogComponent } from './settings-core/settings-core-companies/settings-core-companies-delete-company-dialog/settings-core-companies-delete-company-dialog.component';
import { SettingsCoreCompaniesDeleteFleetAccessDialogComponent } from './settings-core/settings-core-companies/settings-core-companies-delete-fleet-access-dialog/settings-core-companies-delete-fleet-access-dialog.component';
import { SettingsCoreCompaniesFleetAccessAssignedUsersListComponent } from './settings-core/settings-core-companies/settings-core-companies-fleet-access-assigned-users-list/settings-core-companies-fleet-access-assigned-users-list.component';
import { SettingsCoreCompaniesListComponent } from './settings-core/settings-core-companies/settings-core-companies-list/settings-core-companies-list.component';
import { SettingsCoreCompaniesComponent } from './settings-core/settings-core-companies/settings-core-companies.component';
import { SettingsCoreDriverAddVehicleDialogComponent } from './settings-core/settings-core-driver/settings-core-driver-add-vehicle-dialog/settings-core-driver-add-vehicle-dialog.component';
import { SettingsCoreDriverAssignedDriverListComponent } from './settings-core/settings-core-driver/settings-core-driver-assigned-driver-list/settings-core-driver-assigned-driver-list.component';
import { SettingsCoreDriverCreateDriverDialogComponent } from './settings-core/settings-core-driver/settings-core-driver-create-new-driver-dialog/settings-core-driver-create-new-driver-dialog.component';
import { SettingsCoreDriverDeleteDriverDialogComponent } from './settings-core/settings-core-driver/settings-core-driver-delete-driver-dialog/settings-core-driver-delete-driver-dialog.component';
import { SettingsCoreDriverListComponent } from './settings-core/settings-core-driver/settings-core-driver-list/settings-core-driver-list.component';
import { SettingsCoreDriverReleaseVehicleDialogComponent } from './settings-core/settings-core-driver/settings-core-driver-release-vehicle-dialog/settings-core-driver-release-vehicle-dialog.component';
import { SettingsCoreDriverResetPasswordDialogComponent } from './settings-core/settings-core-driver/settings-core-driver-reset-password-dialog/settings-core-driver-reset-password-dialog.component';
import { SettingsCoreDriverComponent } from './settings-core/settings-core-driver/settings-core-driver.component';
import { SettingsCoreEventStrategiesFleetStrategiesDialogComponent } from './settings-core/settings-core-event-strategies/settings-core-event-strategies-fleet-strategies-dialog/settings-core-event-strategies-fleet-strategies-dialog.component';
import { SettingsCoreEventStrategiesComponent } from './settings-core/settings-core-event-strategies/settings-core-event-strategies.component';
import { SettingsCoreEventStrategiesCreateDialogComponent } from './settings-core/settings-core-event-strategies/settings-core-event-strategies-create-dialog/settings-core-event-strategies-create-dialog.component';
import { SettingsCoreEventStrategiesDeleteDialogComponent } from './settings-core/settings-core-event-strategies/settings-core-event-strategies-delete-dialog/settings-core-event-strategies-delete-dialog.component';
import { SettingsCoreEventStrategiesListComponent } from './settings-core/settings-core-event-strategies/settings-core-event-strategies-list/settings-core-event-strategies-list.component';
import { SettingsCoreFleetsDeleteVehicleDialogComponent } from './settings-core/settings-core-fleets/settings-core-fleets-delete-vehicle-dialog/settings-core-fleets-delete-vehicle-dialog.component';
import { SettingsCoreFleetsFleetComponent } from './settings-core/settings-core-fleets/settings-core-fleets-fleet/settings-core-fleets-fleet.component';
import { SettingsCoreFleetsNewBranchDialogComponent } from './settings-core/settings-core-fleets/settings-core-fleets-new-branch-dialog/settings-core-fleets-new-branch-dialog.component';
import { SettingsCoreFleetsNewVehicleDialogComponent } from './settings-core/settings-core-fleets/settings-core-fleets-new-vehicle-dialog/settings-core-fleets-new-vehicle-dialog.component';
import { SettingsCoreFleetsVehicleEventStrategiesListModalComponent } from './settings-core/settings-core-fleets/settings-core-fleets-vehicle-event-strategies-list-modal/settings-core-fleets-vehicle-event-strategies-list-modal.component';
import { SettingsCoreFleetsVehicleEventStrategyModalComponent } from './settings-core/settings-core-fleets/settings-core-fleets-vehicle-event-strategy-modal/settings-core-fleets-vehicle-event-strategy-modal.component';
import { SettingsCoreFleetsVehicleComponent } from './settings-core/settings-core-fleets/settings-core-fleets-vehicle/settings-core-fleets-vehicle.component';
import { SettingsCoreFleetsComponent } from './settings-core/settings-core-fleets/settings-core-fleets.component';
import { SettingsCoreNotificationsEditDialogComponent } from './settings-core/settings-core-notifications/settings-core-notifications-edit-dialog/settings-core-notifications-edit-dialog.component';
import { SettingsCoreNotificationsComponent } from './settings-core/settings-core-notifications/settings-core-notifications.component';
import { SettingsCoreProfileEditDialogComponent } from './settings-core/settings-core-profile/settings-core-profile-edit-dialog/settings-core-profile-edit-dialog.component';
import { SettingsCoreProfileMFADialogComponent } from './settings-core/settings-core-profile/settings-core-profile-mfa-dialog/settings-core-profile-mfa-dialog.component';
import { SettingsCoreProfilePasswordDialogComponent } from './settings-core/settings-core-profile/settings-core-profile-password-dialog/settings-core-profile-password-dialog.component';
import { SettingsCoreProfileComponent } from './settings-core/settings-core-profile/settings-core-profile.component';
import { SettingsCoreReportsDeleteReportComponent } from './settings-core/settings-core-reports/settings-core-reports-delete-report/settings-core-reports-delete-report.component';
import { SettingsCoreReportsListComponent } from './settings-core/settings-core-reports/settings-core-reports-list/settings-core-reports-list.component';
import { SettingsCoreReportsNewReportComponent } from './settings-core/settings-core-reports/settings-core-reports-new-report/settings-core-reports-new-report.component';
import { SettingsCoreReportsSelectedReportComponent } from './settings-core/settings-core-reports/settings-core-reports-selected-report/settings-core-reports-selected-report.component';
import { SettingsCoreReportsComponent } from './settings-core/settings-core-reports/settings-core-reports.component';
import { SettingsCoreRolesAssignedUsersListComponent } from './settings-core/settings-core-roles/settings-core-roles-assigned-users-list/settings-core-roles-assigned-users-list.component';
import { ModulesListElementComponent } from './settings-core/settings-core-roles/settings-core-roles-create-role-dialog/modules-list-element/modules-list-element.component';
import { SettingsCoreRolesCreateRoleDialogComponent } from './settings-core/settings-core-roles/settings-core-roles-create-role-dialog/settings-core-roles-create-role-dialog.component';
import { SettingsCoreRolesCreateUserDialogComponent } from './settings-core/settings-core-roles/settings-core-roles-create-user-dialog/settings-core-roles-create-user-dialog.component';
import { SettingsCoreRolesDeleteUserDialogComponent } from './settings-core/settings-core-roles/settings-core-roles-delete-user-dialog/settings-core-roles-delete-user-dialog.component';
import { SettingsCoreRolesResetMfaDialogComponent } from './settings-core/settings-core-roles/settings-core-roles-reset-mfa-dialog/settings-core-roles-reset-mfa-dialog.component';
import { SettingsCoreRolesResetPasswordDialogComponent } from './settings-core/settings-core-roles/settings-core-roles-reset-password-dialog/settings-core-roles-reset-password-dialog.component';
import { SettingsCoreRolesUsersListComponent } from './settings-core/settings-core-roles/settings-core-roles-users-list/settings-core-roles-users-list.component';
import { SettingsCoreRolesComponent } from './settings-core/settings-core-roles/settings-core-roles.component';
import { SettingsCoreSafetyScoresAssignDialogComponent } from './settings-core/settings-core-safety-scores/settings-core-safety-scores-assign-dialog/settings-core-safety-scores-assign-dialog.component';
import { SettingsCoreSafetyScoresCreateDialogComponent } from './settings-core/settings-core-safety-scores/settings-core-safety-scores-create-dialog/settings-core-safety-scores-create-dialog.component';
import { SettingsCoreSafetyScoresScoringDetailsComponent } from './settings-core/settings-core-safety-scores/settings-core-safety-scores-scoring-details/settings-core-safety-scores-scoring-details.component';
import { SettingsCoreSafetyScoresComponent } from './settings-core/settings-core-safety-scores/settings-core-safety-scores.component';
import { SettingsCoreSharedClipsEditDialogComponent } from './settings-core/settings-core-shared-clips/settings-core-notifications-edit-dialog/settings-core-shared-clips-edit-dialog.component';
import { SettingsCoreSharedClipsComponent } from './settings-core/settings-core-shared-clips/settings-core-shared-clips.component';
import { SettingsCoreComponent } from './settings-core/settings-core.component';
import { SettingsTopComponent } from './settings-top/settings-top.component';
import { SettingsEffects } from './settings.effects';
import { SETTINGS_FEATURE_KEY, settingsReducer } from './settings.reducer';
import { StepperComponent } from './settings-core/settings-core-fleets/settings-core-fleets-new-vehicle-dialog/stepper/stepper.component';
import { VehicleModeSelectionComponent } from './settings-core/settings-core-fleets/settings-core-fleets-new-vehicle-dialog/vehicle-mode-selection/vehicle-mode-selection.component';
import { VehicleLookupComponent } from './settings-core/settings-core-fleets/settings-core-fleets-new-vehicle-dialog/add-vehicle/steps/vehicle-lookup/vehicle-lookup.component';
import { GeneralInfoComponent } from './settings-core/settings-core-fleets/settings-core-fleets-new-vehicle-dialog/add-vehicle/steps/general-info/general-info.component';
import { ProvidersSelectComponent } from './settings-core/settings-core-fleets/settings-core-fleets-new-vehicle-dialog/add-vehicle/steps/providers-select/providers-select.component';
import { SuccessAddVehicleComponent } from './settings-core/settings-core-fleets/settings-core-fleets-new-vehicle-dialog/add-vehicle/steps/success-add-vehicle/success-add-vehicle.component';
import { SettingsCoreProvidersComponent } from './settings-core/settings-core-providers/settings-core-providers.component';
import { SettingsCoreProvidersCreateProviderDialogComponent } from './settings-core/settings-core-providers/settings-core-providers-create-provider-dialog/settings-core-providers-create-provider-dialog.component';
import { SettingsCoreFleetsVehicleCommissionComponent } from './settings-core/settings-core-fleets/settings-core-fleets-vehicle-commission/settings-core-fleets-vehicle-commission.component';
import { SettingsCoreFleetsVehicleCommissionVerifyTemplateComponent } from './settings-core/settings-core-fleets/settings-core-fleets-vehicle-commission/settings-core-fleets-vehicle-commission-verify-template/settings-core-fleets-vehicle-commission-verify-template.component';
import { SettingsCoreFleetsCommissionNoEventDialogComponent } from './settings-core/settings-core-fleets/settings-core-fleets-vehicle-commission/settings-core-fleets-commission-no-event-dialog/settings-core-fleets-commission-no-event-dialog.component';
import { SettingsCoreAppSettingsComponent } from './settings-core/settings-core-app-settings/settings-core-app-settings.component';
import { SettingsCoreAppAddSettingsComponent } from './settings-core/settings-core-app-settings/settings-core-app-add-settings/settings-core-app-add-settings.component';

@NgModule({
  declarations: [SettingsCoreSafetyScoresScoringDetailsComponent, SettingsCoreCompaniesDeleteFleetAccessDialogComponent, SettingsCoreCompaniesCreateFleetAccessDialogComponent, SettingsCoreCompaniesCompanyComponent, SettingsCoreCompaniesFleetAccessAssignedUsersListComponent, SettingsCoreCompaniesDeleteCompanyDialogComponent, SettingsCoreCompaniesComponent, SettingsCoreCompaniesListComponent, SettingsCoreCompaniesCreateCompanyDialogComponent, SettingsCoreComponent, SettingsTopComponent, SettingsCoreProfileComponent, SettingsCoreFleetsComponent, SettingsCoreFleetsVehicleComponent, SettingsCoreFleetsNewBranchDialogComponent, SettingsCoreFleetsNewVehicleDialogComponent, SettingsCoreSharedClipsComponent, SettingsCoreNotificationsComponent, SettingsCoreSafetyScoresComponent, SettingsCoreProfilePasswordDialogComponent, SettingsCoreProfileMFADialogComponent, SettingsCoreProfileEditDialogComponent, SettingsCoreSafetyScoresAssignDialogComponent, SettingsCoreSafetyScoresCreateDialogComponent, SettingsCoreRolesComponent, SettingsCoreRolesCreateRoleDialogComponent, ModulesListElementComponent, SettingsCoreRolesUsersListComponent, SettingsCoreRolesAssignedUsersListComponent, SettingsCoreRolesCreateUserDialogComponent, SettingsCoreRolesDeleteUserDialogComponent, SettingsCoreRolesResetPasswordDialogComponent, SettingsCoreRolesResetMfaDialogComponent, SettingsCoreDriverComponent, SettingsCoreDriverCreateDriverDialogComponent, SettingsCoreDriverListComponent, SettingsCoreDriverResetPasswordDialogComponent, SettingsCoreDriverDeleteDriverDialogComponent, SettingsCoreDriverAssignedDriverListComponent, SettingsCoreNotificationsEditDialogComponent, SettingsCoreSharedClipsEditDialogComponent, SettingsCoreFleetsDeleteVehicleDialogComponent, SettingsCoreFleetsFleetComponent, SettingsCoreReportsComponent, SettingsCoreReportsListComponent, SettingsCoreReportsNewReportComponent, SettingsCoreReportsDeleteReportComponent, SettingsCoreReportsSelectedReportComponent, SettingsCoreDriverAddVehicleDialogComponent, SettingsCoreDriverReleaseVehicleDialogComponent, SettingsCoreAdminNoticesComponent, SettingsCoreNewNoticesComponent, SettingsCoreNoticeListComponent, SettingsCoreDeleteNoticeComponent, SettingsCoreFleetsVehicleEventStrategiesListModalComponent, SettingsCoreFleetsVehicleEventStrategyModalComponent, StepperComponent, VehicleModeSelectionComponent, VehicleLookupComponent, GeneralInfoComponent, ProvidersSelectComponent, SuccessAddVehicleComponent, SettingsCoreEventStrategiesComponent, SettingsCoreEventStrategiesListComponent, SettingsCoreEventStrategiesCreateDialogComponent, SettingsCoreEventStrategiesDeleteDialogComponent, SettingsCoreEventStrategiesFleetStrategiesDialogComponent, StepperComponent, VehicleModeSelectionComponent, SettingsCoreProvidersComponent, SettingsCoreProvidersCreateProviderDialogComponent, SettingsCoreFleetsVehicleCommissionComponent, SettingsCoreFleetsVehicleCommissionVerifyTemplateComponent, SettingsCoreAdminsCreateDialogComponent, SettingsCoreAdminsComponent, SettingsCoreFleetsCommissionNoEventDialogComponent, SettingsCoreAppSettingsComponent, SettingsCoreAppAddSettingsComponent],
  imports: [StoreModule.forFeature(SETTINGS_FEATURE_KEY, settingsReducer), EffectsModule.forFeature([SettingsEffects]), SharedModule, CdkMenuModule, FormsModule, CdkAccordionModule, NgOptimizedImage, MatDialogModule, DialogModule, CdkDropList, CdkDrag, CdkDragHandle, MatMenuModule, TimeSelectControlModule, MatRadioModule, MatProgressSpinnerModule, MatIconModule, SelectControlCounterModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class SettingsModule {}
